mod e_tag_tests;
mod enum_as_update_case;
mod enum_as_where_case;
mod enum_generator_tests;
mod table_schema_tests;
mod test_basic_cases;
mod test_json_field;
mod test_json_hashmap_dto;
mod where_model;
pub use test_basic_cases::*;
